### ISSUE TITLE
This hook locks up my box!

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwarrior-shift-all-recurrence-hook#1]
taskwarrior-shift-all-recurrence-hook is an important workaround, but it might need updating after hook API changes and tasklib upgrades. 
It causes a process runaway, don't have much more diagnostic, but I had to kill it and delete it.

**Comment by linuxcaffe** [comment]
the real solution, imho, is something like https://bug.tasktools.org/browse/TW-238, but I would use this hook in the meantime.

**Comment by tbabej** [comment]
Please try the update version.

**Comment by tbabej** [comment]
Fixed.
